# Generated by Django 3.0.4 on 2020-04-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0017_auto_20200407_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga_cv',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Area'),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Cargo'),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Municipio'),
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Tipo_Identificacion'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carguecv.Departamento'),
        ),
    ]
